spring.application.name=cognodb
server.port=${PORT:8081}

cognodb.uri=${COGNODB_URI:bolt+s://db-b34659a0.bravo.databases.cognodb.com}
cognodb.username=${COGNODB_USER:cognodb}
cognodb.password=${COGNODB_PASSWORD:5d10bfe863db598eb84e858bee162278}
