spring.application.name=cognodb
server.port=${PORT:8081}

cognodb.uri=${COGNODB_URI:bolt+s://db-b34659a0.bravo.databases.cognodb.com}
cognodb.username=${COGNODB_USER:cognodb}
cognodb.password=ENC(ThMWqs2gZ4U+FflzCEDpL5VVHoN6JAjHDtfRtv0JftFRHg4ENeGIJBB2OXDeszlEVat3KkZ0QkDl/An/3DTCLqoeGd1vxJZzTeQ6kPdEmRI=)
