spring.application.name=supplychain-api
server.port=${PORT:8081}

server.servlet.context-path=/api
api.version.one=/v1

# Standard Spring Boot Neo4j Configuration
spring.neo4j.uri=bolt+s://db-b34659a0.bravo.databases.cognodb.com
spring.neo4j.authentication.username=cognodb
spring.neo4j.authentication.password=ENC(63mPnTZCN91zXU95ztEAL7hUb3YOQ4R3tmaZIjWbqK4XmsAyNeqC4+/aI6MnylYPP9zHviui1lGr+8Lk49n65tPiSq5MW42wo/kQPZoDmDo=)


spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB
spring.servlet.multipart.file-size-threshold=8MB

#logging.level.com.cognodb.supplychain=DEBUG
#logging.level.org.springframework.data.neo4j.cypher=DEBUG


logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan}:%L %clr(:){faint} %m%n%wEx

logging.file.name=/home/neelkamal/log/supplychain.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${PID:- } --- [%15.15t] %-40.40logger{39}:%L : %m%n%wEx
